### ISSUE TITLE
Receiving Forbidden during export

### ISSUE THREAD

**Issue by LeagueOfPoro** [CommunityDragon/CDTB#65]
Hi,
I am trying to export the latest patch. However, the URL `http://l3cdn.riotgames.com/releases/live/solutions/league_client_sln/releases/releaselisting` is returning 403.

I am getting the same result when I'm trying to access that URL in a browser. Is the URL correct?

Thanks!

Full trace:
```powershell
PS C:\MyProjects\CDTB> pipenv run python -m cdragontoolbox export latest
Traceback (most recent call last):
  File "C:\Users\PC\.pyenv\pyenv-win\versions\3.10.6\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\PC\.pyenv\pyenv-win\versions\3.10.6\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\MyProjects\CDTB\cdragontoolbox\__main__.py", line 500, in <module>
    main()
  File "C:\MyProjects\CDTB\cdragontoolbox\__main__.py", line 496, in main
    globals()[f"command_{args.command.replace('-', '_')}"](parser, args)
  File "C:\MyProjects\CDTB\cdragontoolbox\__main__.py", line 264, in command_export
    patch = storage.patch(None if args.patch == 'latest' else args.patch)
  File "C:\MyProjects\CDTB\cdragontoolbox\storage.py", line 318, in patch
    return next(it)
  File "C:\MyProjects\CDTB\cdragontoolbox\storage.py", line 302, in patches
    for _, group in itertools.groupby(self.patch_elements(stored=stored), key=lambda e: e.version):
  File "C:\MyProjects\CDTB\cdragontoolbox\rads.py", line 131, in patch_elements
    elem = peeker.peek()
  File "C:\MyProjects\CDTB\cdragontoolbox\rads.py", line 107, in peek
    self.cur = next(self.it)
  File "C:\MyProjects\CDTB\cdragontoolbox\rads.py", line 120, in gen_solution_elements
    for sv in solution.versions(stored=stored):
  File "C:\MyProjects\CDTB\cdragontoolbox\rads.py", line 196, in versions
    listing = self.storage.request_text(f"{self.path}/releaselisting").splitlines()
  File "C:\MyProjects\CDTB\cdragontoolbox\storage.py", line 234, in request_text
    r.raise_for_status()
  File "C:\Users\PC\.virtualenvs\CDTB-Cb147n_d\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://l3cdn.riotgames.com/releases/live/solutions/league_client_sln/releases/releaselisting
```

**Comment by benoitryder** [comment]
The README is outdated. This command tries to use the obsolete RADS storage format that is not available anymore.

This command should work (where `cdn` is a directory where CDN files will be stored).
```
python3 -m cdragontoolbox export -s patcher:cdn latest
```

**Comment by LeagueOfPoro** [comment]
Got the download working, thank you.
